### ISSUE TITLE
Enable TLS / https

### ISSUE THREAD

**Issue by jonathancross** [CommonAccord/Cmacc-Org#19]
Would be great to add a secure certificate so users can be sure that we are connected to the right site.  Let's Encrypt is recommended: https://letsencrypt.org

**Comment by HazardJ** [comment]
Hi, sorry it was hard to find the real origin of commonaccord.org.  There is a lot of historical/dead material lying around.  And I just moved the canonical home for the /G/ prose object repos from Cmacc-Source to the long-time main site -  Cmacc-Org.

Interested in the problem and solution, but not clear on them.  I presume the use case where the problem is presented is that someone makes a contract by reference to a URL at CommonAccord.org, but the absence of certificates means that another site could be spoofing commonaccord.org.   Is that right?

**Comment by jonathancross** [comment]
Thanks for the quick response.

> another site could be spoofing commonaccord.org

Yes, in general that is my concern.

I have not spent much time thinking about all reasons why this makes sense, but these days all websites should be enabling https.  This ensures that users will be seeing what you published. A MITM attack without TLS is effortless for ISP / Gov / Wifi router / Tor exit node / employer, etc.  It also helps with passive surveillance in that connections and content are not in plain text.

Considering it is free, the question is more **_why not_** use https?  :-)
